### ISSUE TITLE
Recognize aliases when resolving inherited icons

### ISSUE THREAD

**Issue by vanto** [yoyurec/logseq-awesome-links#1]
**Idea**
Currently, inherited page icons only work for the exact page reference. It would be nice if this plugin would also take aliases into account until https://github.com/logseq/logseq/issues/3763 might be solved.

**Comment by yoyurec** [comment]
can you provide pages content and to recreate?
and desirable result - "i have page X it has props Y, aliast to Z, want to see icon W"

**Comment by yoyurec** [comment]
check latest update!

**Comment by vanto** [comment]
Thanks for the prompt response. It does not do what I expected, maybe I didn't put it precisely. Here is my scenario:

### People.md
```
icon:: 👤
```

### Elon Musk.md
```
page-type:: [[People]]
alias:: Elon
```

When I now write something like, only `Elon Musk` get the icon but not `Elon`.
`Lorem ipsum dolor sit [[Elon Musk]], consectetur adipiscing elit. Ut ex dui, elementum et [[Elon]] in, pretium elementum odio. Phasellus rhoncus rutrum justo sed malesuada.`

Thanks, HTH

**Comment by yoyurec** [comment]
oh, i though you have:

**People.md**
```
icon:: 👤
alias:: ppl
```

**Elon Musk.md**
```
page-type:: [[People]]
```

**Comment by yoyurec** [comment]
will try...

**Comment by yoyurec** [comment]
should be something like:
* try icon from link
* if not, try to go link alias to original page and take icon 
* if not, try to take inherited from props page icon
* if not, try to go to page props inherited alias

**Comment by yoyurec** [comment]
uhhh.... it was challenging )))
check latest release!

* original page with icon
* aliased page
* original page with inherited props-as-page
* aliased page with inherited props-as-page
* original page with inherited props-as-alias

**PS:** aliased page with inherited props-as-alias not covered yet, cose to complex rare case with possible performance issues



check latest update!

**Comment by vanto** [comment]
Awesome, this works! Thanks for the fast implementation.

**Comment by yoyurec** [comment]
i'm not so much using aliases.... so case "original page with inherited props-as-alias" (which i've implemented first, wrongly) - maybe delete it? isn't it rare?
b'cose EACH link checks 4 times (( but can be 3 )))

**Comment by vanto** [comment]
Is this the scenario from https://github.com/yoyurec/logseq-awesome-links/issues/1#issuecomment-1264305068? I would not need that. I, too, think it is a rather rare use case.
