### ISSUE TITLE
Adds twice the icon on journal page titles

### ISSUE THREAD

**Issue by knoopx** [yoyurec/logseq-awesome-links#10]
**Info:**
- OS: linux
- Logseq ver: 0.8.8
- Plugin ver: 1.9.4
- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**

when visiting back and forth journal pages, the journal icon is added twice on page title

**Screenshots**
![image](https://user-images.githubusercontent.com/100993/195993803-7ca0fe68-a077-47d4-a16d-6f6a97de7b91.png)

**Comment by yoyurec** [comment]
which them are you using?

**Comment by knoopx** [comment]
default logseq light theme

**Comment by yoyurec** [comment]
check latest 1.9.5

**Comment by knoopx** [comment]
updated straight to 1.9.7 and the problem is fixed. thank you!
