### ISSUE TITLE
Feature request: hide `color` property like an `title` property hides by Logseq itself

### ISSUE THREAD

**Issue by stdword** [yoyurec/logseq-awesome-links#14]
**Idea**
Logseq hides technical properties like `icon`, `title`, `filters` etc.
`color` property is also "technical" so could be hidden too.

**Screenshots**
<img src="https://user-images.githubusercontent.com/1984175/196703434-168ff365-447f-4a40-960d-14757b4573f6.png" width="30%">

**Comment by yoyurec** [comment]
this will be in next AwesomeUI release )

**Comment by yoyurec** [comment]
shipped!
https://github.com/yoyurec/logseq-awesome-ui/releases/tag/v1.3.0
