### ISSUE TITLE
Calendar icon renders with a new line outside Journals 

### ISSUE THREAD

**Issue by andremann** [yoyurec/logseq-awesome-links#15]
**Info:**
- OS: MacOS
- Logseq ver: 0.8.9
- Plugin ver: 1.9.7
- Theme name: default dark with awesome UI installed

- [x] ⚠ Do i have issue with DISABLED my `custom.css`? it's empty

**Description:**
A line feed is introduced after the calendar icon on a daily page when accessed directly outside Journals

**To Reproduce:**
When I select Journals all the daily pages render fine (see image 1).
However, when I click on a date, this leads to the relevant daily page and a new line feed is added after the calendar icon (see image 2).

**Expected behavior:**
The calendar icon and the date are on the same line

**Screenshots**
Image 1
<img width="847" alt="Screenshot 2022-10-20 at 14 21 59" src="https://user-images.githubusercontent.com/5096918/196948307-7743054d-0821-4688-8635-034ad12532e5.png">

Image 2
<img width="847" alt="Screenshot 2022-10-20 at 14 22 08" src="https://user-images.githubusercontent.com/5096918/196948522-5157cfc8-6d71-4b3c-934d-3da19daddc90.png">
**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
latest Logseq update broke things,,, working on this

**Comment by yoyurec** [comment]
check latest v1.10.0

**Comment by andremann** [comment]
seems OK. Thanks.
