### ISSUE TITLE
icon font is not in the same height with title

### ISSUE THREAD

**Issue by Sanly** [yoyurec/logseq-awesome-links#16]
"line-height: 1.2em;" of ".title .awLi-icon" should be changed to "line-height: 1.5;" to make the icon font in the same height with title.

before:
![icon font](https://user-images.githubusercontent.com/9320187/197126929-3f1f992c-cec5-479e-93b2-d3624fe19edc.png)

after:
![icon font2](https://user-images.githubusercontent.com/9320187/197127333-3d323ed7-4745-42f4-a7a2-f8e555285f1b.png)

**Comment by yoyurec** [comment]
latest Logseq 0.8.9 & latest AwLinks?

**Comment by yoyurec** [comment]
fixed

**Comment by joaosimuai** [comment]
I'm having the same problem in page titles with custom icons in `icon::` (both url and asset). Using `<img ... style="vertical-align:value"` corrects it, I think, but I don't know if it's the proper solution
