### ISSUE TITLE
Page icons will gone when "Enable icon/color for internal pages" is turned on

### ISSUE THREAD

**Issue by Gitbreast** [yoyurec/logseq-awesome-links#21]
**Info:**
- OS: MacOS
- Logseq ver: 0.8.9
- Plugin ver: 1.10.5
- Theme name: not important

- [ ] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
When awesome-links works with awesome-ui, tick the "Show default page icons on left sidebar favs/recent?" in awesome-ui, and "Enable icon/color for internal pages?" in awesome-links in the same time. The "Enable icon" setting will override the "Show default icons" setting, as a result, the default page icons would not show out.

**To Reproduce:**
 ...Just as above.

**Expected behavior:**
 ...The default page icons will show out.

**Screenshots**

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
not sure you want to see both "AwLinks" icons and default Logseq... cose it will double them.

![image](https://user-images.githubusercontent.com/137919/198815243-6db2636f-e3fa-43a1-9476-722d187c6d8d.png)

and yes - when AwLinks icons enabled - it hides native Logseq icons at all, providing own mechanism for displaying them

**Comment by yoyurec** [comment]
i can suggest only 1 solution (in addition to do nothing 😉) - provide option (diong more conflicts with Banners plugin ahaha) for AwLinks to set the default icon (as for journals)

**Comment by Gitbreast** [comment]
@yoyurec Oh I see. Is it means it has no way to show default icons and custom icons in the same time? And definitely yes, an option to keep both of them is great! A non symmetrical line up looks uncomfortable😂

**Comment by yoyurec** [comment]
new default Logseq page icon "П" look so ugly and unspeakable ((

**Comment by yoyurec** [comment]
check latest release! 

![image](https://user-images.githubusercontent.com/137919/198827647-ea39a221-fc93-4995-892e-c109c19df5d2.png)

![image](https://user-images.githubusercontent.com/137919/198827888-aad66d7e-e21e-4496-864f-fbaeb1d08c83.png)

**Comment by Gitbreast** [comment]
> new default Logseq page icon "П" look so ugly and unspeakable ((

OMG, I never notice that if u don't mention it.

**Comment by Gitbreast** [comment]
> check latest release! default page icons for sidebar/tabs
> 
> ![image](https://user-images.githubusercontent.com/137919/198827647-ea39a221-fc93-4995-892e-c109c19df5d2.png)
> 
> ![image](https://user-images.githubusercontent.com/137919/198827888-aad66d7e-e21e-4496-864f-fbaeb1d08c83.png)

Thanks for this! Brilliant works!
