### ISSUE TITLE
Icons for Google Docs, Spreadsheets, Slides

### ISSUE THREAD

**Issue by ahpatel** [yoyurec/logseq-awesome-links#22]
**Idea**
I often link Google Docs, Spreadsheets, Slides, etc.  They all show the generic Google logo.  But, I notice that you do render photos.google.com and mail.google.com with Google Photos and Gmail icons.  

Is it possible to also add a Docs (docs.google.com/document), Sheets (docs.google.com/spreadsheets) and Slides (docs.google.com/presentation) icon as well?

**Screenshots**
<img width="308" alt="Screenshot 2022-11-08 at 3 25 25 PM" src="https://user-images.githubusercontent.com/9514136/200668072-1f7e932e-504e-47f4-ac5c-5b7306886bff.png">

**Comment by yoyurec** [comment]
favicons is using Google API, so...
`https://www.google.com/s2/favicons?domain=docs.google.com&sz=32`

same for another provider: `https://icons.duckduckgo.com/ip3/docs.google.com.ico`

**Comment by yoyurec** [comment]
solution - parse urls and set icon manually for such cases

**Comment by yoyurec** [comment]
check latest release 😎
