### ISSUE TITLE
Cannot uninstall plugin

### ISSUE THREAD

**Issue by kerim** [yoyurec/logseq-awesome-links#26]
**Info:**
- OS: MacOS
- Logseq ver: 0.8.15
- Plugin ver: 1.14.3
- Theme name: Dev (but problem exists if I disable Dev as well).

**Description:**
I disabled and uninstalled the app via the plugins preferences, and checked that it was no longer listed in plugins.edn, but it still appears as installed and activated every time I restart the app. The icons appear as well. 

**To Reproduce:**
Install the plugin, then attempt to uninstall? (Can't uninstall so can't tell if this is reproducible every time, but other people on Discord have reported having similar issues.)

**Expected behavior:**
Uninstalling the plugin should uninstall the plugin.

**Comment by yoyurec** [comment]
can't reproduce ((
have you solve it somehow?
check Logseq plugins folder `%USER%/.logseq/plugins`

**Comment by kerim** [comment]
I did solve this some time ago, but I forget how I did it.
