### ISSUE TITLE
Can not display icon

### ISSUE THREAD

**Issue by wickkk119** [yoyurec/logseq-awesome-links#27]
**Idea**
The icon font can't load in my mac. Which font do I need to install? I found the corresponding css snippet in the developer tools, the font-family is var(--icon-font).

Thank you for your dedication.

**Screenshots**
<img width="145" alt="image" src="https://user-images.githubusercontent.com/43113136/207722445-447550a5-5321-4249-a749-74d5d0c31c4a.png">

**Comment by yoyurec** [comment]
@wickkk119  do you still have issue?
which icon set you are trying to use? Nerd icon?

**Comment by williamlwclwc** [comment]
I'm having the same issue, switching the fonts in the awesome-styler plugin will work with most of the icons in the Nerd icon cheat sheet, but some of them still cannot be displayed e.g. latex icon. Do I need to manually change the fonts to use nerd icons?

**Comment by DorianStrasser** [comment]
I also have this problem. None of the Nerdicons work. Can I provide anything to help identify the problem?

**Comment by yoyurec** [comment]
@DorianStrasser i'm planning to investigate in a few days... will ask then )

**Comment by stalagmi** [comment]
same issue with the Nerdicons - i have installed the Fira Code Nerd Font, but from the cheat sheet only a minority of icons show up, many of which are labeled as obsolete

**Comment by yoyurec** [comment]
@DorianStrasser @stalagmi  can you propvide names of non working icons?

**Comment by yoyurec** [comment]
if icons obsolete - then they updated/deleted them, question not ot me ((

**Comment by yoyurec** [comment]
> I'm having the same issue, switching the fonts in the awesome-styler plugin...

AwStyler with it's font have no any relation to AwLinks.
AwLinks is using "nerd version" (none of AwStyler fonts are) + font stored in assets. Will try to refresh TTF file...

**Comment by yoyurec** [comment]
@williamlwclwc i need to know icon name

**Comment by yoyurec** [comment]
Nn page props edit mode ICONS will not be shown - nerd fonts do not applied to this aerea, cose they are monospaced and whole block will look weird!
Test icon on page title after switching from/to (to refresh) page! 
 
![image](https://user-images.githubusercontent.com/137919/220766276-6d302793-6ff6-4248-bcdf-16c662a33ece.png)

**Comment by stalagmi** [comment]
> @DorianStrasser @stalagmi @williamlwclwc @wickkk119 can you propvide names of non working icons?

for me, it would not work for any icons from the cheatlist that had -md- in the name. Only -mdi- would work, or -fa-. This seems fixed now though, I can see the -md- ones too! Thanks for the update :)

**Comment by yoyurec** [comment]
super!
