### ISSUE TITLE
Inherit page icon from URL favicon

### ISSUE THREAD

**Issue by jsvensson** [yoyurec/logseq-awesome-links#28]
**Idea**
I frequently use a `url` property for pages. It would be neat if I could set a page property that the plugin can use to fetch that favicon to use as the icon for the page.

Ideally it would also play nice with inherited page icons, letting the favicon url override it. In the screenshot below I have a `Software` page that sets the current floppy icon that the `Spotify` page inherits; this idea would add a (customizable) property with a URL whose favicon the plugin would use instead.

**Screenshots**
<img width="300" alt="image" src="https://user-images.githubusercontent.com/450287/214963966-d9086366-ca3b-4147-8ef2-45fe6834aaee.png">

**Comment by yoyurec** [comment]
just use `icon::` prop with img tag & link to favicon ))
check https://github.com/yoyurec/logseq-awesome-links/issues/17

favison URLs - `https://www.google.com/s2/favicons?sz=32&domain=[HOST-HERE]`
icon prop `<img style="width:1em;" src="[IMAGE-URL-HERE]">`

so props for ex. `icon:: <img style="width:1em;" src="https://www.google.com/s2/favicons?sz=32&domain=spotify.com">`

PS: to automatize process - just add this to template

**Comment by yoyurec** [comment]
Adding feature to the plugin do not sound good as every person has their own notes style - in your case AwesomeLinks need to "read" `url` field, I'm personally using `source`, somebody uses `web`, etc... 

To make it work with any prop - a new settings field (so you can type 'url' there as inherited prop name) should be intruduced... but so rare usage case means somebody in furute will ask abot own rules and fields and plugin became a mess (((

**Comment by yoyurec** [comment]
![image](https://user-images.githubusercontent.com/137919/216999536-a693abd9-723c-4db8-84ad-bc1b944cc152.png)

not perfect aligned, but i will check issues on next week. for now working on AwesomeUI plugin...
