### ISSUE TITLE
Disabling favicons for external links doesn't work

### ISSUE THREAD

**Issue by itsamemarkus** [yoyurec/logseq-awesome-links#3]
**Info:**
- OS: Windows 10+11
- Logseq ver: 0.8.8
- Plugin ver: 1.5.1
- [y ] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
`Show site favicon for external links?` deselect doesn't work

**To Reproduce:**
deselect `Show site favicon for external links?` and paste a link that has a favicon

**Expected behavior:**
No external icon shown and no outgoing requests to favicons.

When you're behind an external logging firewall you maybe don't want to all those requests going out revealing every base URL of a link you have on a page to that firewall.

**Screenshots**

![image](https://user-images.githubusercontent.com/34944988/195007799-6298a311-b918-418f-a3a1-cb14ddb5c83e.png)

**Comment by yoyurec** [comment]
do you have issue after Logseq restart?

**Comment by yoyurec** [comment]
check latest release!

**Comment by itsamemarkus** [comment]
works! Thanks :)
