### ISSUE TITLE
Icon to support Apple Mail links

### ISSUE THREAD

**Issue by AvijeetPrasad** [yoyurec/logseq-awesome-links#31]
**Idea**
Links to Apple mail, which have the format `[Apple mail](message://%3c29580-0B7-482-AA0-8A7E11C757@com%3e)` are not rendered properly.

**Screenshots**
Add some pictures to get the idea if needed

![](https://cdn.discordapp.com/attachments/974900076751228928/1077919364386390066/Screenshot_2023-02-22_at_12.45.21.png)

**Comment by yoyurec** [comment]
done

**Comment by yoyurec** [comment]
re-done )
