### ISSUE TITLE
Add Jira atlassian.net domain for favicon

### ISSUE THREAD

**Issue by bcohen44** [yoyurec/logseq-awesome-links#32]
**Idea**
Add Jira Cloud favicon for atlassian.net domain

**Screenshots**
Add some pictures to get the idea if needed
![image](https://user-images.githubusercontent.com/6190190/221034136-09f876b1-1caf-4ef7-b523-ce7d9299cdce.png)

**Attach files**

**Comment by yoyurec** [comment]
isn't atlassian.net have no own site favicon?
isn't jira have no icon?
can you provide exmple of full link?

**Comment by bcohen44** [comment]
Each company gets a <company>.atlassian.net domain, so not sure what static link to point to.

**Comment by yoyurec** [comment]
maybe there is some pattern?
[COMPANY-NAME].atlassian.net/jira/[other-dynamic-stuff] ?

**Comment by yoyurec** [comment]
done!

**Comment by yoyurec** [comment]
![image](https://user-images.githubusercontent.com/137919/221194324-8603d640-5ac6-4696-9ea5-32ddacf8ec8d.png)

**Comment by bcohen44** [comment]
Super, thank you @yoyurec !

**Comment by bcohen44** [comment]
I updated, but this link is not showing the jira icon (not a real link for privacy of my company)

https://comapnyname.atlassian.net/browse/XYZ-7528

**Comment by yoyurec** [comment]
> I updated, but this link is not showing the jira icon (not a real link for privacy of my company)
> 
> https://comapnyname.atlassian.net/browse/XYZ-7528

of course if will not work - you haven't provided url so i added own

**Comment by yoyurec** [comment]
check update
