### ISSUE TITLE
allow user to create favicon for domains

### ISSUE THREAD

**Issue by bcohen44** [yoyurec/logseq-awesome-links#33]
**Idea**
Instead of hardcoding the favicons, allow the user (thru settings) to point to an icon, and user a domain, to customize their own favicons.

**Screenshots**
Add some pictures to get the idea if needed

**Attach files**
Add (via drag-n-drop) .zip with `.md` files if it help me with experiments

**Comment by yoyurec** [comment]
not planned b'cose it can be tricky for users
