### ISSUE TITLE
icons for paths to local file system

### ISSUE THREAD

**Issue by MarkusPic** [yoyurec/logseq-awesome-links#35]
**Idea**
I often add links to my local file system to point to the folder of a project. I would like to have an icon for a folder to distinguish between links to the web and links to a folder.

A big bonus would be if links to local files would get the icon as shown (or similar) in the file manager.

**Screenshots**
HTTPS links get a default icon similar to "🌐" and I would like that FILES:// links get an icon similar to "📂".

PC: Thanks for the already great plugin :)

**Comment by yoyurec** [comment]
![image](https://user-images.githubusercontent.com/137919/224016112-568d9800-5e04-4250-965a-99865bb18bdd.png)

ka-boom!
