### ISSUE TITLE
Enable internal links would break the aligning of left sidebar

### ISSUE THREAD

**Issue by Gitbreast** [yoyurec/logseq-awesome-links#36]
**Info:**
- OS: MacOS
- Logseq ver: 0.8.18
- Plugin ver: 1.15.4
- Theme name: null

- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
Enable internal links -- no matter page default props' icon using nerd or tablet-icons -- would break the aligning of left sidebar (with emoji icon page in it). But Logseq default page icon works well with emoji icon.

**To Reproduce:**
Enable internal links.
Add a page using emoji icon to favorites.
Add a normal page to favorites. Check.

**Expected behavior:**
 Align better.

**Screenshots**
Noted the first words with inline icons start from different positions:
<img width="218" alt="image" src="https://user-images.githubusercontent.com/96460796/224110979-ad178057-f714-4349-8c42-77884ed1e4f4.png">
<img width="225" alt="image" src="https://user-images.githubusercontent.com/96460796/224111266-398ab89a-b576-4b6c-ad49-152758dae86f.png">
<img width="218" alt="image" src="https://user-images.githubusercontent.com/96460796/224114830-5b1c099e-d2ad-404e-aa01-bf8b8cbe3cbb.png">

If disable internal links and enable Logseq default page icon, it would show like this, start in same positions:
<img width="224" alt="image" src="https://user-images.githubusercontent.com/96460796/224112259-6ca636f6-3f9b-472d-8242-9d80f86e56da.png">

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
what about now? check latest

**Comment by Gitbreast** [comment]
> what about now? check latest

tabler-icon seems better
<img width="215" alt="image" src="https://user-images.githubusercontent.com/96460796/224215969-6363acd9-38ba-42d2-8f9b-3ac459d67d61.png">

nerd still visible, check the "L"
<img width="233" alt="image" src="https://user-images.githubusercontent.com/96460796/224216342-331c0da4-f2f4-42da-b810-634982e0dad2.png">

**Comment by yoyurec** [comment]
what about if i will kill Nerd suport? )
are using it? theit set looks ugly and inconsistency, cose from different icons pack...
how many icons missed in Tabler? is it possible to switch only to them?
just need users stats about this...

**Comment by Gitbreast** [comment]
@yoyurec Yeah killing Nerd sounds ok with me. Tabler has lots more icons. Nerd seems just has a better "calendar" in it.

One more thing with Tabler. Emoji fits well in a row, auto width and height, aligns in center. But Tabler usually aligns on top left of its father element, has a little bias.
Emoji:
<img width="217" alt="image" src="https://user-images.githubusercontent.com/96460796/224392107-1efc23e8-7b60-4d30-bd44-9286fab67406.png">  <img width="152" alt="image" src="https://user-images.githubusercontent.com/96460796/224392191-89c1592e-5bfe-44bf-8c6a-fd0d7e8303b8.png">
Tabler:
<img width="111" alt="image" src="https://user-images.githubusercontent.com/96460796/224393637-d5536b1e-de47-48ae-ac63-a6ee1f7fc3a3.png"> <img width="156" alt="image" src="https://user-images.githubusercontent.com/96460796/224393762-8e35a845-3880-4789-83f6-5d7f69bb6589.png">

**Comment by yoyurec** [comment]
fixed: titles & tabs
both: tabler + emoji
