### ISSUE TITLE
Support icon for zotero:// ?

### ISSUE THREAD

**Issue by wanicca** [yoyurec/logseq-awesome-links#38]
**Idea**
Currently, the links to `zotero://` seem to lack the icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/22728527/224818344-ac34c34e-e603-49d8-8aa1-b8a9390cb890.png)

**Example Link**
`[Bridging the Gap between Language Model and Reading Comprehension: Unsupervised MRC via Self-Supervision](zotero://select/items/0_IG8J86YA)`

**Comment by yoyurec** [comment]
![image](https://user-images.githubusercontent.com/137919/224822758-711eb528-f95e-45fc-8d2d-d3a5afa93479.png)

**Comment by yoyurec** [comment]
or red one 
![image](https://user-images.githubusercontent.com/137919/224823432-da62d688-8944-449c-be86-b4b05fc6be51.png)

**Comment by yoyurec** [comment]
done. red )
