### ISSUE TITLE
Can't really disable favicon rendering on external links in some specific case

### ISSUE THREAD

**Issue by stdword** [yoyurec/logseq-awesome-links#4]
**Info:**
- OS: MacOS Monterey 12.6
- Logseq ver: 0.8.8
- Plugin ver: 1.5.1
- [x] ⚠ Do i have issue with DISABLED my `custom.css`?
- [ ] ⚠ Do i have issue with DISABLED **other plugins**?

**Priority**: LOW, because there is work around (see it at the bottom)

**Description:**
Can't really disable favicon rendering on **external** links, when:
 * icon rendering on **internal** links remain turned on (seems like it is important)
 * `Logseq Plugin Automatic URL title` ([→](https://github.com/0x7b1/logseq-plugin-automatic-url-title)) is enabled

**Note 1**: When `Logseq Plugin Automatic URL title` is disabled — everything works fine.

**Note 2**: `Logseq Plugin Automatic URL title` renders the favicon too and it's way of rendering more sharpy (I prefer it — see at the left):
<img src="https://user-images.githubusercontent.com/1984175/195337078-f34c5249-963c-4e95-a208-ad378a350e04.png" width="50%">
Probably the reason is **retina** display on my mac. Here is the difference in favicons HTML:
<img src="https://user-images.githubusercontent.com/1984175/195342250-b88b0818-267a-4837-a0e6-615e1f4fdb09.png" width="30%">
So we can change the size for retina displays. But this is not the way of solving issue, because I need another functionality of `Logseq Plugin Automatic URL title` too: fetching header titles. So disabling this plugin is not an option.

**To Reproduce:**
1. Install and enable `Logseq Plugin Automatic URL title`
2. Install and enable `Awesome Links`
3. Set the settings for `Awesome Links` like this:
    <img src="https://user-images.githubusercontent.com/1984175/195334449-4e79d40c-de97-4042-8c8e-700c31335779.png" width="36%">
4. Reload the page (⌘+R ) 
5. Rendering of icons still turned on:
    <img src="https://user-images.githubusercontent.com/1984175/195337078-f34c5249-963c-4e95-a208-ad378a350e04.png" width="50%">

**Expected behavior:**
 Properly working of all `Awesome Links` plugin settings with enabled `Logseq Plugin Automatic URL title`.

**Workaround for now:**
`custom.css`:
```css
img.awLinks-link-icon {
    display: none !important;
}
```

**Comment by yoyurec** [comment]
> Plugin ver: 1.5.1

latest is 1.5.3, favicons was fixed yesterday https://github.com/yoyurec/logseq-awesome-links/issues/3

**Comment by stdword** [comment]
Nice! Thank you! I've check the version 1.5.4 — both fixed: size of favicons and setting

A big thank you for the cool plugins!
