### ISSUE TITLE
cannot disable plugin from the plugin settings toggle

### ISSUE THREAD

**Issue by ndc33** [yoyurec/logseq-awesome-links#43]
**Info:**
- OS: windows
- Logseq ver: 0.91
- Plugin ver: v1.15.16
- Theme name: AwesomeStyler

**Description:**
A clear and concise description of what the bug is......
cannot disable plugin from the plugin settings toggle

**To Reproduce:**
toggle the plugin to disabled. Close and then restart logseq. Plugin is now enabled.

**Comment by yoyurec** [comment]
enabling & disabling plugin IS NOT a part of its code//functionality, just using app API
looks like it's a Logseq bug... ((
or something with your configs.
try to delete plugin & install again
