### ISSUE TITLE
Page icons all display wrong icons

### ISSUE THREAD

**Issue by bitbonk** [yoyurec/logseq-awesome-links#46]
**Info:**
- OS: macOS Catalina (also happens on Windows 11)
- Logseq ver: 0.9.3
- Plugin ver: v1.15.16
- Theme name: none

**Description:**
When using page icons that I copied from nerd font and paste it into Logseq, Logseq does not display the icon that I actually copied.

**To Reproduce:**
Create a page type with an `icon::` property.
Go to https://www.nerdfonts.com/cheat-sheet and click on copy icon for the "group" icon.
<img width="424" alt="Screenshot 2023-04-19 at 23 07 22" src="https://user-images.githubusercontent.com/418030/233200413-5d7764fe-5557-4539-b4d6-e6969178aa60.png">

Now paste this icon into the `icon::` property

**Actual behavior:**
The icon looks totally different in Logseq.
<img width="335" alt="image" src="https://user-images.githubusercontent.com/418030/233201153-2829a314-90a7-4a71-99fe-a38a7eea04e7.png">

**Expected behavior:**
The icon looks exactly like the the one we copied from nerd font

This happened ever since I updated Logseq and the plugin. Now all my previously setup `icon::`s look wrong.

**Comment by stdword** [comment]
Same issues for me =(

**Comment by bitbonk** [comment]
I think this problems comes from the fact that [v1.15.7](https://github.com/yoyurec/logseq-awesome-links/releases/tag/v1.15.7) made the new Tabler icon set the default, which seems to be a breaking change for everyone who had the plugin installed already. 

To solve this you need to change the config from Tabler back to Nerdfont:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/418030/233833272-794d9828-8f76-4d2f-ac0c-a13b27935c37.png">

**Comment by stdword** [comment]
@bitbonk Thank you! It helps 🙏
