### ISSUE TITLE
Provide inheritance through hierarchy

### ISSUE THREAD

**Issue by stdword** [yoyurec/logseq-awesome-links#7]
**Idea**
1. Create a page with icon:
    <img src="https://user-images.githubusercontent.com/1984175/195591520-7233f77b-a3ee-4bfb-8cde-e396e421b571.png" width="15%">
2. Create a page that inherits an icon (my inheritance look at the `tags` property):
    <img src="https://user-images.githubusercontent.com/1984175/195591783-5875ea37-7dd4-4ac0-bb6d-b1e4d49cd59f.png" width="18%">
3. Check the icon rendering on sub page:
    <img src="https://user-images.githubusercontent.com/1984175/195592014-8d401a65-22f7-4684-be99-5e0050931326.png" width="25%">

**Expected behaviour**:
1. All sub pages can inherit whole icon configuration from root page
2. All sub pages can inherit whole icon configuration from the rightmost parent page (in case of root page config overrided in one of the sub pages)

**Comment by yoyurec** [comment]
if you check the code - there are a lot of icon search attempts alreqady. adding more can do perf issues...
at least searching through all hierarchy. what if just add 1 level (most left) checking?
