### ISSUE TITLE
Icon rendering in `Hierarchy` section doesn't work

### ISSUE THREAD

**Issue by stdword** [yoyurec/logseq-awesome-links#8]
**Info:**
- OS: MacOS Monterey 12.6
- Logseq ver: 0.8.8
- Plugin ver: 1.6.0
- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
Icon rendering on internal links in `Hierarchy` section doesn't work.

**To Reproduce:**
 1. Make an icon on root page of some hierarchy:
     <img src="https://user-images.githubusercontent.com/1984175/195593654-0a103b30-1b1b-44aa-8250-317c6060d1c4.png" width="25%">
2. Look at the `Hierarchy` section at the bottom of the page:
     <img src="https://user-images.githubusercontent.com/1984175/195593866-f615994a-ef87-4ae0-a430-e4ce1f708bac.png" width="25%">

**Expected behavior:**
Rendering an icon just like in other cases.

**Comment by yoyurec** [comment]
check 1.7.0
