### ISSUE TITLE
Link text coloring

### ISSUE THREAD

**Issue by stdword** [yoyurec/logseq-awesome-links#9]
**Idea**
No coloring (like now):
<img src="https://user-images.githubusercontent.com/1984175/195607352-66f3f107-55b4-476d-a2b8-c7247e24d797.png" width="30%">

With coloring:
   <img src="https://user-images.githubusercontent.com/1984175/195607594-cdd73212-6d50-4f0e-a8f2-ad69c633cfd9.png" width="28%">

Color information located in page's properties:
<img width="385" src="https://user-images.githubusercontent.com/1984175/195607961-9a505a49-27aa-46e2-bf96-6e742f2580ad.png">

PS Inspired by `Logseq Reference Styles` plugin ([→](https://github.com/benjaffe/logseq-reference-styles)) and `Obsidian Supercharged Links` plugin ([→](https://github.com/mdelobelle/obsidian_supercharged_links))

**Comment by yoyurec** [comment]
check latest **1.8.0**
https://github.com/yoyurec/logseq-awesome-links#-page-colors

**Comment by yoyurec** [comment]
yepp, no icon, no color for current release )

**Comment by yoyurec** [comment]
why do so many HEX tests if it clearly written in readme - "widthout #". willl also add "without quotes" ))

**Comment by yoyurec** [comment]
no Banners support yet... later

**Comment by stdword** [comment]
<img width="779" alt="Link text coloring · Issue #9 · yoyurec:logseq-awesome-links 2022-10-14 01-03-40" src="https://user-images.githubusercontent.com/1984175/195719600-18b9c2b6-b140-4695-ae64-353633656e61.png">

**Comment by stdword** [comment]
+ one more issue: I didn't disable icon for journal pages in global config:
![image](https://user-images.githubusercontent.com/1984175/195720665-db65d2a8-be68-4626-8b48-e9c20768896b.png)

It seems to be broken

**Comment by yoyurec** [comment]
added any CSS colors (in doublequotes⚠), color without icons, journal icon is back - v1.8.2 

_in case you want to treat me to coffee ☕, you know how to do it )))_

**Comment by yoyurec** [comment]
PS: no page title, no sidebar coloring

**Comment by yoyurec** [comment]
sidebar, title, tab colors added in 1.8.3

**Comment by stdword** [comment]
I've caught color link in sidebar once, but cannot reproduce =(
<img width="1101" alt="Logseq 2022-10-14 02-22-37" src="https://user-images.githubusercontent.com/1984175/195728846-48243c0c-1fc4-44ba-a5af-5b2b6b084f1d.png">

**Comment by yoyurec** [comment]
![image](https://user-images.githubusercontent.com/137919/195729524-dcb41ce8-baa5-420e-a0de-6ce3d22c0a57.png)
journal only default icon. no customizations - no custom color, no custon icon via props. only icon via settings

**Comment by yoyurec** [comment]
> I've caught color link in sidebar once, but cannot reproduce =(
restart Logseq

**Comment by stdword** [comment]
It is the first thing Ive done)

Reproduced!
<img width="471" alt="test color ok — green 2022-10-14 02-36-23" src="https://user-images.githubusercontent.com/1984175/195730413-50f5be0f-ee1b-4154-b761-ffb10623409a.png">

with icon == no color
without icon == with color

**Comment by yoyurec** [comment]
maybe bigger load timeouts will fix it. 1.8.4

**Comment by stdword** [comment]
No, in 1.8.4 still →
`with icon == no color`
`without icon == with color`

**Comment by stdword** [comment]
> journal only default icon. no customizations - no custom color, no custom icon via props. only icon via settings

It is logical, you're right. Custom colors for journals should be via settings, like an icon.

**Comment by stdword** [comment]
![image](https://user-images.githubusercontent.com/1984175/195930110-67a69423-af77-437e-8b33-66ae049a1b16.png)

**Comment by stdword** [comment]
And there is one more pattern with inheritance:
1. if I make a project page with icon and blue color:
    <img src="https://user-images.githubusercontent.com/1984175/195931442-03d69535-1781-45ae-b83b-f8a2375db898.png" width="30%">
2. And page, that inherits icon and color:
    <img src="https://user-images.githubusercontent.com/1984175/195931676-d647c3aa-d85d-425b-b418-c572e360d2ff.png" width="50%">
3. Then inherited page at the side bar renders OK, but project fails to render color:
    <img src="https://user-images.githubusercontent.com/1984175/195931848-ebec5965-d30c-43f5-9805-10348531b259.png" width="40%">

**Comment by yoyurec** [comment]
> Custom colors for journals should be via settings

could be, not should )

**Comment by yoyurec** [comment]
sidebar works buggy, and refreshing on edit to heavy for perf. maybe better to disable it...

**Comment by yoyurec** [comment]
fixed 🐱‍👤

**Comment by yoyurec** [comment]
BTW, in latest 1.9.5 journal page have same possibility as common pages - own props icon/color

**Comment by stdword** [comment]
Wow!! It works amazing! All cases are ✅
Thank you so much!

**Comment by stdword** [comment]
> could be, not should )

Well, a few arguments for global color option for journal pages:
1. Just to support global icon option: color is meta info about link decoration to, like an icon (so do banner and its options in `Banners`)
2. In case I don't like theme's color and want to change it (now I must change color for every page separately)

What do you think?

**Comment by yoyurec** [comment]
1 - agree, cose there is no parent page to inherit from
2- you can install "Awesome Styler" _theme-o-pugin_, select "Logseq default" preset, clone it and customize everything 😎
![image](https://user-images.githubusercontent.com/137919/196058709-8360ba6e-d30d-4bb7-bb85-f0011fa9ee9d.png)

**Comment by stdword** [comment]
Thank for styler! But in this case it forces me to change theme. For now I enjoy [these ones](https://piotrsss.github.io/logseq-tools/public/#/bujo-themes).

**Comment by stdword** [comment]
Found some bugs:
1. Hierarchy coloring was broken:
<img src="https://user-images.githubusercontent.com/1984175/196061755-6a2a6104-a701-4a9c-b979-06a08f9ccf42.png" width="30%">

2. If I made inheritance throught the alias — coloring doesn't work for links:
<img src="https://user-images.githubusercontent.com/1984175/196061806-468b51cd-e40c-4ece-9541-adcaa3a0a6da.png" width="30%">
<img src="https://user-images.githubusercontent.com/1984175/196061830-da156e71-c17a-435a-9125-ff85c30f5fb8.png" width="60%">
<img src="https://user-images.githubusercontent.com/1984175/196061864-347f09e4-07a3-475d-b912-017fe9304ac1.png" width="20%">

**Comment by yoyurec** [comment]
> Thank for styler! But in this case it forces me to change theme. For now I enjoy [these ones](https://piotrsss.github.io/logseq-tools/public/#/bujo-themes).

you can recreate any theme colors ))

**Comment by stdword** [comment]
> 1 - agree, cose there is no parent page to inherit from

Do you have a plan to add it?

**Comment by yoyurec** [comment]
already in local project, will deploy with bugfixing soon...
![image](https://user-images.githubusercontent.com/137919/196560803-0b8d7e4f-4f6b-47f9-a4a0-200862977672.png)
